# config.yaml
#TODO: connect to config.py

project:
  name: "MigiBot"
  version: "1.0.0"
  api_version: "/api/v1"

paths:
  base_dir: null  # Will be set programmatically
  markdown_dir: "markdown"
  faiss_index_dir: "vector_stores/faiss_index"
  vector_store_dir: "vector_stores"

llm:
  provider: "ollama"
  model_name: "llama3.1:8b"
  temperature: 0.0
  max_tokens: null
  streaming: true
  additional_params: {}

embedding:
  provider: "openai"
  model_name: "text-embedding-3-small"
  additional_params: {}

vector_store:
  provider: "faiss"
  collection_name: "migi_collection"
  additional_params: {}

chunking:
  chunk_size: 500
  chunk_overlap: 50